name: Ubuntu GCC CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    strategy:
      matrix:
        cxx_standard: [17, 20]
        build_type: ["Release", "Debug"]
        configuration: [
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"7"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"8"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"9"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"10"},

          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"9"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"10"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"11"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"12"}
        ]

    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{matrix.configuration.UBUNTU_VERSION}}

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt-get install -y \
            software-properties-common ca-certificates \
            ninja-build make zlib1g-dev wget \
            python3-pip python3 python3-dev python3-setuptools

          add-apt-repository ppa:ubuntu-toolchain-r/test

          bash ./docker/gcc/pyinstall.sh $(cat /etc/os-release | grep -a UBUNTU_CODENAME | sed -e 's/UBUNTU_CODENAME=//g')

          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir "conan==2.*" cmake==3.25.0

      - name: Install compiler
        run: |
          apt update && apt-get install -y gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} 90 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-${{matrix.configuration.TOOLCHAIN_VERSION}} \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-${{matrix.configuration.TOOLCHAIN_VERSION}}
          update-alternatives --config gcc

      - name: Configure CMake
        env:
          CC: gcc-${{matrix.configuration.TOOLCHAIN_VERSION}}
          CXX: g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          BUILD_TYPE: ${{matrix.build_type}}
          CXX_STANDARD: ${{matrix.cxx_standard}}
        run: |
          conan profile detect --force
          conan install . --output-folder=. -s build_type=${BUILD_TYPE} --build=missing

          cmake -S . -B build/${BUILD_TYPE} -GNinja \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DCMAKE_CXX_STANDARD=${CXX_STANDARD} \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_CXX_COMPILER=${CXX} \
            -DALLOW_EXAMPLES=ON \
            -DALLOW_TESTS=ON \
            -DENABLE_TESTS_MEASUREMENTS=ON \
            -DALLOW_BENCHMARK=ON \
            -DEXCEPTIONS_DISABLE=ON \
            -DRTTI_DISABLE=ON \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/build/${BUILD_TYPE}/generators/conan_toolchain.cmake

      - name: Build
        run: cmake --build build/${{ matrix.build_type }}

      - name: Test
        working-directory: build/${{ matrix.build_type }}
        run: ctest --rerun-failed --output-on-failure

      - name: Analyze dependencies
        working-directory: build/${{ matrix.build_type }}
        run: ldd bin/dataflow